### ISSUE TITLE
Make the BrowserEnvironment have the gaze cursor enabled on mobile by default.

### ISSUE THREAD

**Issue by capnmidnight** [NotionTheory/Primrose#115]
In order for the gaze cursor to work on mobile devices, the person implementing a script must set a configuration parameter named `useGaze` to the [`isMobile`](https://github.com/NotionTheory/Primrose/blob/master/src/flags/isMobile.js) flag when setting up their [`BrowserEnvironment`](https://github.com/NotionTheory/Primrose/blob/master/src/Primrose/BrowserEnvironment.js)

All that needs to be done is to change the BrowserEnvironment's DEFAULTS object at the end of the file. It current has `useGaze` set to false. It should be set to `isMobile`. Also, look for the line `import isiOS from "../flags/isiOS";` and add a line below it to import the `isMobile` flag from the same flags directory.

**Comment by hurbraa** [comment]
Submitted a pull request (Submitting straight to master is ok for minor bugfixes according to submission guidelines?)

I'm new to git so I hope you could point out if I did something wrong.

**Comment by capnmidnight** [comment]
Thanks for the PR!
