### ISSUE TITLE
Sky position update should be in BrowserEnvironment's `update` function, not `moveGround`.

### ISSUE THREAD

**Issue by capnmidnight** [NotionTheory/Primrose#122]
[In the BrowserEnvironment class, in the moveGround function, there is a line of code for keeping the sky box fixed to the user](https://github.com/NotionTheory/Primrose/blob/master/src/Primrose/BrowserEnvironment.js#L375), so that the user is never able to clip through the sky box and see an unrendered area behind.

This line of code should be moved to be between [these two lines of code](https://github.com/NotionTheory/Primrose/blob/master/src/Primrose/BrowserEnvironment.js#L343-L344).

The `if` statement surrounding that line of code on lines 374 and 376 should just be deleted. The update cycle depends on the sky object being created in the first place, so we don't have to test for its existence.

Progress:
- [ ] delete the `if` statement that surrounds the line of code at line 375.
- [ ] move the line of code from (what is now) line 374 to line 344.

**Comment by upodroid** [comment]
Hello

I have fixed the issue.

**Comment by capnmidnight** [comment]
Thanks!
