### ISSUE TITLE
Project Setup documentation

### ISSUE THREAD

**Issue by hurbraa** [NotionTheory/Primrose#126]
I am fairly confident I did the setup correctly.

Currently the Project Setup guide in the readme doesn't seem to actually include app.js in the website, so only an empty page with 'hello world' is displayed when `npm start` is entered.

I think it would be a good idea to update the readme scripts to actually execute the app.js that the setup guide asks the user to make.

I created a pull request to demonstrate this - just close these if the example setup is not intended to run like that.

**Comment by capnmidnight** [comment]
Thanks for the catch. I'm going to leave this issue open for now, as I have plans to write a more detailed document for getting started from the ground-up.

**Comment by kbouw** [comment]
Hey @hurbraa - you can now try the new [setup guide](https://github.com/NotionTheory/Primrose/wiki/Working-on-Primrose) which provides a base template for getting started and auto runs a development server.

I'm going to close this issue. If you experience any trouble during the setup process in the link referenced above, please create a separate issue.
