### ISSUE TITLE
Shadows demo specifies an environment option that is actually the default value.

### ISSUE THREAD

**Issue by capnmidnight** [NotionTheory/Primrose#132]
The demo showing how to make objects with shadows [specifies a value for the `useGaze` option](https://github.com/NotionTheory/Primrose/blob/master/demos/shadows/app.js#L2). This value is unnecessary, as this is the default value as specified [the BrowserEnvironment defaults](https://github.com/NotionTheory/Primrose/blob/master/src/Primrose/BrowserEnvironment.js#L1462). Delete line #2 in the Shadows demo.

**Comment by lougeniaC64** [comment]
@capnmidnight I can take this.

**Comment by lougeniaC64** [comment]
Wait, just read the description of the first-timers-only label.  I should leave this for someone else.

**Comment by pdnellius** [comment]
I'll take it! :)
